services:
  upnext-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_URL: http://localhost:3000
        NEXT_PUBLIC_API_URL: http://localhost:4000/api
    environment:
      APP_ENV: production
      NEXT_PUBLIC_APP_NAME: UpNext
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
      INTERNAL_API_URL: http://upnext-backend:4000/api
    ports:
      - "3000:3000"
